# SPDX-FileCopyrightText: 2023 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "**"
precedence = "override"
SPDX-FileCopyrightText = "Stoney Jackson <dr.stoney@gmail.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
